 FROM xccszu/openjdk1.8
 MAINTAINER Solay Solayappan
 COPY SpringMicroserviceS1-0.0.1-SNAPSHOT.jar SpringMicroserviceS1-0.0.1-SNAPSHOT.jar
 ENTRYPOINT ["java","-jar","/SpringMicroserviceS1-0.0.1-SNAPSHOT.jar"]
 EXPOSE 8080 5672